Host_URL = "https://[::]:443;http://[::]:80;https://0.0.0.0:443;http://0.0.0.0:80;"

[PostgreSQL]
Server_Address = "127.0.0.1:5432"
API_Provider_Username = "postgres"
API_Provider_Password = "R1t5DT5rn/b1R6r0e7JctXGAn2FUshQSuHAFmVOwAyM="
